services:
  backend:
    build: ./backend
    container_name: homecam-backend
    ports:
      - "8005:8000"
    devices:
      - "/dev/video0:/dev/video0"
    volumes:
      - ./recordings:/recordings
    restart: unless-stopped
    environment:
      - CAMERA_DEVICE=/dev/video0
      - RECORDINGS_DIR=/recordings
      - MOCK_CAMERA=false
      - TZ=Asia/Jakarta

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: http://192.168.1.10:8005
    container_name: homecam-frontend
    ports:
      - "3005:3000"
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      - TZ=Asia/Jakarta
