services:
  backend:
    build: ./backend
    container_name: homecam-backend
    ports:
      - "8005:8000"
    privileged: true
    volumes:
      - ./recordings:/recordings
      - /dev:/dev
    restart: unless-stopped
    environment:
      - CAMERA_DEVICE=/dev/video0
      - RECORDINGS_DIR=/recordings
      - MOCK_CAMERA=false
      - TZ=Asia/Jakarta

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: https://api.rizqikevin.my.id
    container_name: homecam-frontend
    ports:
      - "3005:3000"
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      - TZ=Asia/Jakarta
