#!/usr/bin/env bash
#
# HomeCam Server self-hosted runner setup wizard.
# Run this on the production server (robot@192.168.1.10) or any machine
# with SSH access.
#
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

banner "HomeCam CI/CD Setup"

# ── Stage 1: Verify prerequisites ────────────────────────────────────────

stage "Check prerequisites"
say "Checking Docker, Compose, and optional gh CLI on this machine..."
say ""

ERRORS=0
if command -v docker >/dev/null 2>&1; then
  step "Docker $(docker --version | head -1) ✓"
else
  warn "Docker not found — install Docker first"
  ERRORS=$((ERRORS + 1))
fi

if docker compose version >/dev/null 2>&1; then
  step "Docker Compose $(docker compose version --short 2>/dev/null || echo '?') ✓"
else
  warn "Docker Compose plugin not found — install it first"
  ERRORS=$((ERRORS + 1))
fi

if command -v gh >/dev/null 2>&1; then
  step "GitHub CLI $(gh --version | head -1) ✓"
  if gh auth status >/dev/null 2>&1; then
    step "gh authenticated ✓"
  else
    note "gh not authenticated; runner verification will use the browser."
  fi
else
  note "gh CLI not found; runner verification will use the browser."
fi

if [ "$ERRORS" -gt 0 ]; then
  say ""
  if ! confirm "There are issues. Continue anyway?"; then
    say "Fix the issues above and re-run this script."
    exit 1
  fi
fi

pause

# ── Stage 2: Create GitHub Environment ───────────────────────────────────

stage "Create GitHub Environment 'production'"
say "This environment serializes deploys (one at a time)."
say ""
open_url "https://github.com/rizqikevin/homecam-server/settings/environments"
say ""
step "Click 'New environment'."
step "Name it: production"
step "Click 'Configure environment'."
step "Under 'Deployment branches and tags', choose 'Selected branches and tags'."
step "Add rule: main"
say ""
note "This prevents deploys from feature branches and serializes production deploys."
pause "Done configuring the environment?"

# ── Stage 3: Register self-hosted runner ─────────────────────────────────

stage "Register self-hosted runner"
say "The runner connects outbound to GitHub — no ports to open."
say ""
open_url "https://github.com/rizqikevin/homecam-server/settings/actions/runners/new"
say ""
step "Select OS: Linux, Architecture: x64"
step "Follow the commands shown on the page:"
say ""
say "  1. Create a directory:"
say "     mkdir actions-runner && cd actions-runner"
say ""
say "  2. Download & extract (copy the exact curl command from the page)"
say ""
say "  3. Configure the runner:"
say "     ./config.sh --url https://github.com/rizqikevin/homecam-server --token <TOKEN_FROM_PAGE>"
say ""
say "  When prompted:"
say "    - Runner group: press Enter (default)"
say "    - Runner name: press Enter or type 'homecam-prod'"
say "    - Labels: type 'self-hosted,linux' then press Enter"
say "    - Work folder: press Enter (default _work)"
say ""

pause "Runner configured?"

say ""
step "Install as systemd service so it survives reboot:"
say ""
say "  sudo ./svc.sh install"
say "  sudo ./svc.sh start"
say "  sudo ./svc.sh status"
say ""
note "The runner user must be in the 'docker' group:"
say "  sudo usermod -aG docker \$(whoami)"
say "  (logout and login again if needed)"
say ""

pause "Runner service running?"

# ── Stage 4: Verify runner is online ─────────────────────────────────────

stage "Verify"
say "Let's check everything is connected."
say ""
open_url "https://github.com/rizqikevin/homecam-server/settings/actions/runners"
say ""
step "Confirm the runner shows a green 'Idle' status on the Runners page."
say ""

if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  say "  Checking via API..."
  RUNNER_COUNT=$(gh api repos/rizqikevin/homecam-server/actions/runners --jq '.total_count' 2>/dev/null || echo "0")
  if [ "$RUNNER_COUNT" -gt 0 ]; then
    step "Found ${RUNNER_COUNT} runner(s) registered ✓"
  else
    warn "No runners found via API — check the Runners page manually."
  fi
fi

say ""
step "Test: push a commit or trigger a manual deploy from the Actions tab."
say ""
note "CI runs on GitHub-hosted runners (automatic)."
note "CI generates disposable test credentials automatically; no CI password secret is needed."
note "Deploy runs on your self-hosted runner after CI passes on main."
note ""
note "deploy.sh checks for active recordings before restarting containers."
note "If a recording is active, deploy is aborted (re-trigger when idle)."

pause

finish
